accumulate_grad_batches_num: 4
bs: 8
checkpoint_path: /root/gurusmart/Moonshot/initial_experiments/initial_exps_larger_model/only_hsqc_small_model_trial_1/checkpoints/epoch=47-step=41136.ckpt
combine_oneD_only_dataset: false
coord_enc: sce
debug: false
decoder_embed_dim: 384
delete_checkpoint: false
dim_coords:
- 180
- 180
- 24
encoder_embed_dim: 384
epochs: 300
expname: experiment
foldername: test_run
freeze: false
gce_resolution: 1
jittering: 0
load_decoder: false
load_encoder: false
lr: 1.0e-05
metric: val/mean_cosine_similarity
metricmode: max
noam_factor: 1.0
num_decoder_heads: 8
num_decoder_layers: 4
num_encoder_heads: 8
num_encoder_layers: 4
num_workers: 4
only_C_NMR: false
only_H_NMR: false
only_oneD_NMR: false
optional_MW: false
optional_inputs: false
patience: 7
random_seed: 42
scheduler: attention
test: true
train_on_all_info_set: true
transformer_dropout: 0.1
use_C_NMR: true
use_HSQC: true
use_H_NMR: true
use_Jaccard: false
use_MW: true
use_oneD_NMR_no_solvent: true
use_small_model: true
validate: false
warm_up_steps: 4000
wavelength_bounds:
- - 0.01
  - 400.0
- - 0.01
  - 20.0
weight_decay: 0.0
