accumulate_grad_batches_num: 4
bs: 32
checkpoint_path: null
combine_oneD_only_dataset: false
coord_enc: sce
debug: true
decoder_embed_dim: 384
delete_checkpoint: false
dim_coords: &id001
- 180
- 180
- 24
encoder_embed_dim: 384
epochs: 1
expname: experiment
foldername: test_run
freeze: false
gce_resolution: 1
jittering: 0
load_decoder: false
load_encoder: false
lr: 1.0e-05
metric: val/mean_cosine_similarity
metricmode: max
noam_factor: 1.0
num_decoder_heads: 8
num_decoder_layers: 4
num_encoder_heads: 8
num_encoder_layers: 4
num_workers: 4
only_C_NMR: false
only_H_NMR: false
only_oneD_NMR: false
optional_MW: false
optional_inputs: false
p_args:
  accumulate_grad_batches_num: 4
  bs: 32
  checkpoint_path: null
  combine_oneD_only_dataset: false
  coord_enc: sce
  debug: true
  decoder_embed_dim: 384
  delete_checkpoint: false
  dim_coords: *id001
  encoder_embed_dim: 384
  epochs: 1
  expname: experiment
  foldername: test_run
  freeze: false
  gce_resolution: 1
  jittering: 0
  load_decoder: false
  load_encoder: false
  lr: 1.0e-05
  metric: val/mean_cosine_similarity
  metricmode: max
  noam_factor: 1.0
  num_decoder_heads: 8
  num_decoder_layers: 4
  num_encoder_heads: 8
  num_encoder_layers: 4
  num_workers: 4
  only_C_NMR: false
  only_H_NMR: false
  only_oneD_NMR: false
  optional_MW: false
  optional_inputs: false
  patience: 7
  random_seed: 42
  scheduler: attention
  separate_classifier: false
  test: false
  train_on_all_info_set: false
  transformer_dropout: 0.1
  use_Jaccard: false
  use_MW: true
  use_oneD_NMR_no_solvent: false
  validate: false
  warm_up_steps: 4000
  wavelength_bounds: &id002
  - - 0.01
    - 400.0
  - - 0.01
    - 20.0
  weight_decay: 0.0
patience: 7
random_seed: 42
scheduler: attention
selfie_max_len: 455
selfie_symbol_to_idx:
  .: 3
  '[#Branch1]': 4
  '[#Branch2]': 5
  '[#C-1]': 6
  '[#C]': 7
  '[#N+1]': 8
  '[#N]': 9
  '[#O+1]': 10
  '[/C]': 11
  '[123I]': 12
  '[13CH1]': 13
  '[13CH2]': 14
  '[2H]': 15
  '[=13CH1]': 16
  '[=Au]': 17
  '[=Branch1]': 18
  '[=Branch2]': 19
  '[=Branch3]': 20
  '[=CH1-1]': 21
  '[=C]': 22
  '[=N+1]': 23
  '[=N-1]': 24
  '[=NH1+1]': 25
  '[=NH2+1]': 26
  '[=N]': 27
  '[=O+1]': 28
  '[=OH1+1]': 29
  '[=O]': 30
  '[=P+1]': 31
  '[=PH1]': 32
  '[=P]': 33
  '[=Ring1]': 34
  '[=Ring2]': 35
  '[=S+1]': 36
  '[=S]': 37
  '[=SeH1]': 38
  '[=Se]': 39
  '[=Te]': 40
  '[Al+3]': 41
  '[Al]': 42
  '[As+1]': 43
  '[As]': 44
  '[B-1]': 45
  '[B]': 46
  '[Br-1]': 47
  '[Br]': 48
  '[Branch1]': 49
  '[Branch2]': 50
  '[Branch3]': 51
  '[C+1]': 52
  '[C-1]': 53
  '[CH0]': 54
  '[CH1+1]': 55
  '[CH1]': 56
  '[CH2+1]': 57
  '[C]': 58
  '[Ca+2]': 59
  '[Cl+3]': 60
  '[Cl-1]': 61
  '[Cl]': 62
  '[Co+2]': 63
  '[Co]': 64
  '[Cu+2]': 65
  '[END]': 2
  '[F]': 66
  '[Fe+2]': 67
  '[Fe+3]': 68
  '[Fe]': 69
  '[Ga]': 70
  '[H+1]': 71
  '[HH1]': 72
  '[Ho]': 73
  '[I+1]': 74
  '[I-1]': 75
  '[I]': 76
  '[K+1]': 77
  '[K]': 78
  '[Mg+2]': 79
  '[Mg-2]': 80
  '[MgH1+1]': 81
  '[Mg]': 82
  '[Mo+2]': 83
  '[N+1]': 84
  '[N-1]': 85
  '[NH0]': 86
  '[NH1+1]': 87
  '[NH1]': 88
  '[NH2+1]': 89
  '[NH3+1]': 90
  '[N]': 91
  '[Na+1]': 92
  '[NaH1]': 93
  '[Na]': 94
  '[Ni+2]': 95
  '[O+1]': 96
  '[O-1]': 97
  '[OH1-1]': 98
  '[OH2+1]': 99
  '[O]': 100
  '[P+1]': 101
  '[PAD]': 0
  '[PH1]': 102
  '[P]': 103
  '[Ring1]': 104
  '[Ring2]': 105
  '[S+1]': 106
  '[S-1]': 107
  '[SH1+1]': 108
  '[SH1-1]': 109
  '[SH1]': 110
  '[START]': 1
  '[S]': 111
  '[Sb]': 112
  '[Se+1]': 113
  '[SeH1]': 114
  '[SeH2]': 115
  '[Se]': 116
  '[Si]': 117
  '[Sn]': 118
  '[Te]': 119
  '[W]': 120
  '[Zn+2]': 121
separate_classifier: false
test: false
train_on_all_info_set: false
transformer_dropout: 0.1
use_Jaccard: false
use_MW: true
use_oneD_NMR_no_solvent: false
validate: false
warm_up_steps: 4000
wavelength_bounds: *id002
weight_decay: 0.0
